using System;
using System.Collections.Generic;

#nullable disable

namespace sky.recovery.Insfrastructures.Scafolding.SkyEn.Workflow
{
    public partial class WorkflowLogHistory
    {
        public long WlhId { get; set; }
        public long? RshId { get; set; }
        public string TmpTable { get; set; }
        public string WorkflowCode { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string NameCust { get; set; }
        public int? CstAge { get; set; }
        public string CstCif { get; set; }
        public decimal? CstPhoneMobile { get; set; }
        public string CstKtp { get; set; }
        public string CstEmail { get; set; }
        public string ProductCode { get; set; }
        public string InterestRule { get; set; }
        public decimal? ReqAmount { get; set; }
        public decimal? ReqTenor { get; set; }
        public string InterestType { get; set; }
        public string InterestCalculation { get; set; }
        public decimal? LoanAmount { get; set; }
        public decimal? LoanDisbursed { get; set; }
        public decimal? LoanInterest { get; set; }
        public decimal? InstallmentAmount { get; set; }
        public string Decision { get; set; }
        public string RefId { get; set; }
        public string CheckStatus { get; set; }
        public string R770 { get; set; }
        public string ValCheckStatus { get; set; }
        public string R010 { get; set; }
        public decimal? Testing1 { get; set; }
        public string Nik { get; set; }
        public string NikDukcapil { get; set; }
        public DateTime? Dob { get; set; }
        public string NameDukcapil { get; set; }
        public DateTime? DobDukcapil { get; set; }
        public decimal? NameJaroVal { get; set; }
        public string ValDukcapil { get; set; }
        public string RejectCode { get; set; }
        public decimal? LoanTenor { get; set; }
        public int? AskTenor { get; set; }
        public string R009 { get; set; }
        public string Citizenship { get; set; }
        public string MaritalStatus { get; set; }
        public string R016 { get; set; }
        public int? WorkMonth { get; set; }
        public string R011 { get; set; }
        public string R012 { get; set; }
        public decimal? WorkGrossIncome { get; set; }
        public string R013 { get; set; }
        public string R014 { get; set; }
        public decimal? AskLoan { get; set; }
        public string R015 { get; set; }
        public string R017 { get; set; }
        public string R048 { get; set; }
        public string R049 { get; set; }
        public string R065 { get; set; }
        public string R088 { get; set; }
        public string ValGrac { get; set; }
        public string R090 { get; set; }
        public int? ServiceAreaHome { get; set; }
        public int? ServiceAreaWork { get; set; }
        public int? Score { get; set; }
        public string CcComVar2 { get; set; }
        public string CcComVar7 { get; set; }
        public string CcComVar3 { get; set; }
        public string CcComVar4 { get; set; }
        public string CcComVar5 { get; set; }
        public string CcComVar6 { get; set; }
        public string CcComVar1 { get; set; }
        public string LastEducation { get; set; }
        public int? CRestrictedIndustry { get; set; }
        public string RlosCodeSector { get; set; }
        public string ScoreBand { get; set; }
        public string ScoreCrr { get; set; }
        public int? BkMaxMobCc { get; set; }
        public string WorkEmploymentStatus { get; set; }
        public string CRestrictedCom { get; set; }
        public string WorkProfession { get; set; }
        public string IndustryCode { get; set; }
        public int? EgibilityCom { get; set; }
        public string WorkCompanyType { get; set; }
        public string WorkAddressCity { get; set; }
        public string HomeAddressCity { get; set; }
        public int? BkFlag { get; set; }
        public decimal? BkMaxLimitCc { get; set; }
        public string BureauGroup { get; set; }
        public decimal? BkMonthlyCflIncome { get; set; }
        public decimal? FinalIncome { get; set; }
        public int? BkMaxLimitMobCc { get; set; }
        public int? BkMaxMob { get; set; }
        public string BkCategory { get; set; }
        public string ValBureau { get; set; }
        public decimal? BkDbr { get; set; }
        public decimal? BkMonthlyObligation { get; set; }
        public decimal? BkUnsecuredExp { get; set; }
        public decimal? BkOsUnsecuredNoncc { get; set; }
        public decimal? BkTotalLimitCc { get; set; }
        public decimal? MueExternal { get; set; }
        public string R072 { get; set; }
        public string R007 { get; set; }
        public int? BkBlacklistCode { get; set; }
        public int? BkCollectibility { get; set; }
        public int? BkRestructureFlag { get; set; }
        public string R001 { get; set; }
        public int? BkMaxDpd { get; set; }
        public decimal? BkOsDpd { get; set; }
        public string R004 { get; set; }
        public int? BkWorstDelq6 { get; set; }
        public int? BkFreqXdpd6 { get; set; }
        public int? BkWorstDelq12 { get; set; }
        public int? BkFreqWoNoncc12 { get; set; }
        public int? BkFreqWoCc12 { get; set; }
        public decimal? BkOsWoCc { get; set; }
        public int? BkWorstDelq3 { get; set; }
        public string R060 { get; set; }
        public string R008 { get; set; }
        public string AddrDukcapil { get; set; }
        public string GenderDukcapil { get; set; }
        public string KabNameDukcapil { get; set; }
        public string KabIdDukcapil { get; set; }
        public string KelIdDukcapil { get; set; }
        public string KecNameDukcapil { get; set; }
        public string MotherNameDukcapil { get; set; }
        public string KecIdDukcapil { get; set; }
        public string MaritalStsDukcapil { get; set; }
        public string StateIdDukcapil { get; set; }
        public string PobDukcapil { get; set; }
        public string StateNameDukcapil { get; set; }
        public string StatusDukcapil { get; set; }
        public string KelNameDukcapil { get; set; }
        public decimal? LiveYear { get; set; }
        public int? HomeOwnershipMonth { get; set; }
        public decimal? DtiWithout { get; set; }
        public decimal? CoYears { get; set; }
        public string Cat { get; set; }
        public string FlagCard { get; set; }
        public string WorkBusinessPosition { get; set; }
        public string Group1 { get; set; }
        public string HomeOwnershipStatus { get; set; }
        public decimal? HomeMonthlyRentalFee { get; set; }
        public int? MthSncLastAcOpenUnd { get; set; }
        public int? AcctNewLoanL6mUnd { get; set; }
        public decimal? BkAmtNewLoanL6mUnd { get; set; }
        public int? NumUnsecuredLoan { get; set; }
        public decimal? BkUtilCc { get; set; }
        public decimal? BkTotAmt { get; set; }
        public string ComVar1 { get; set; }
        public string Group2 { get; set; }
        public string ComVar2 { get; set; }
        public string ComVar4 { get; set; }
        public decimal? BkLimitSecureLoan { get; set; }
        public string ComVar5 { get; set; }
        public string ComVar3 { get; set; }
        public int? BkLastXdpd { get; set; }
        public int? ReScore { get; set; }
        public string R006 { get; set; }
        public string ScorecardCutoff { get; set; }
        public decimal? MinLoan { get; set; }
        public decimal? MaxLoan { get; set; }
        public string BkCategoryFlag { get; set; }
        public int? MaxMueInt2 { get; set; }
        public int? TotalMue { get; set; }
        public decimal? MaxAssignedLoanAmtMue { get; set; }
        public int? MaxMueInt1 { get; set; }
        public decimal? AssignedLim1 { get; set; }
        public string PlCategory { get; set; }
        public string R098 { get; set; }
        public string MinLoanCutOff { get; set; }
        public decimal? InterestRate { get; set; }
        public decimal? DbrTotal { get; set; }
        public string DbrCutOff { get; set; }
        public decimal? MaxDbr { get; set; }
        public decimal? FinalAssignedLimit { get; set; }
        public int? MaxTenor { get; set; }
        public decimal? MaxInterest { get; set; }
        public decimal? MaxInstallment { get; set; }
        public string ChannelId { get; set; }
        public string Segment { get; set; }
        public string CampaignId { get; set; }
        public string ReferralCode { get; set; }
        public int? BkPefindoScore { get; set; }
        public decimal? Asa { get; set; }
        public string CstFname { get; set; }
        public string CstSex { get; set; }
        public string CstAddress { get; set; }
        public DateTime? CstDob { get; set; }
        public string CstZipcode { get; set; }
        public string CstAddressCity { get; set; }
        public string CstPhoneHome { get; set; }
        public string ListHomeOwnershipCf { get; set; }
        public string CstMaritalStatus { get; set; }
        public int? CstNumberOfChild { get; set; }
        public string CstNpwp { get; set; }
        public string CstMotherMaidenName { get; set; }
        public string CstWorkAddress { get; set; }
        public string CstCompanyName { get; set; }
        public string CstEmploymentNumber { get; set; }
        public decimal? CstWorkIncome { get; set; }
        public string CstWorkPhone { get; set; }
        public string EmploymentType { get; set; }
        public decimal? WorkNumberOfEmployee { get; set; }
        public string SavingAccountName { get; set; }
        public string CstDetailedLoanPurpose { get; set; }
        public string SavingAccount { get; set; }
        public string EmergencyContact { get; set; }
        public string CstEmergencyRelationship { get; set; }
        public string CstEmergencyPhoneMobile { get; set; }
        public string Category { get; set; }
        public string NotesAnalyst { get; set; }
        public string RcMaxAge { get; set; }
        public string RcMinAge { get; set; }
        public string ListKewarganegaraan { get; set; }
        public string RcWni { get; set; }
        public string RcMinincome { get; set; }
        public string RcEmploymentLength { get; set; }
        public string FlagPassGeneral { get; set; }
        public string FlagPassVerification { get; set; }
        public string FlagDecision { get; set; }
        public decimal? RatingScore { get; set; }
        public string RcDedupHr { get; set; }
        public string Keputusan { get; set; }
        public int? LengthOfEmployment { get; set; }
        public string ProductName { get; set; }
        public string ProductVersion { get; set; }
        public decimal? AskDrawdown { get; set; }
        public string CstTypeOfCc { get; set; }
        public string CstOtherBankCc { get; set; }
        public string CstImgDocIncome { get; set; }
        public string CstDocNpwp { get; set; }
        public string CstImgDocEktp { get; set; }
        public string CstImgDocKk { get; set; }
        public string CstDocLegalBusnis { get; set; }
        public string CstDocSupport { get; set; }
    }
}
